services:
  web.api:
    image: web.api
    build:
      context: .
      dockerfile: src/Web.Api/Dockerfile
    ports:
      - "5067:8080"
    volumes:
      # Mount a local folder or Docker volume to persist keys
      - aspnet_keys:/home/app/.aspnet/DataProtection-Keys
    user: "1000:1000"

  postgres:
    image: postgres:17-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=Internship-Platform
    volumes:
      - ./.containers/intern_db:/var/lib/postgresql/data
    ports:
      - "5431:5432"

  migrate:
    image: web.api
    command: dotnet ef database update
    depends_on:
      - postgres
    volumes:
      - aspnet_keys:/home/app/.aspnet/DataProtection-Keys
    user: "1000:1000"

volumes:
  aspnet_keys: